# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"


[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }


[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.pure]
github = "sindresorhus/pure"
use = ["async.zsh", "pure.zsh"]

[plugins.zshrc-local-sync]
local = '~/.zsh.site'
use = ['sync.zsh']
apply = ['source']

[plugins.zshrc-local-defer]
local = '~/.zsh.site'
use = ['defer.zsh']
apply = ['defer']

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.zshrc-local-defer-after-compinit]
local = '~/.zsh.site'
use = ['defer-after-compinit.zsh']
apply = ['defer']

